/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections/index'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections/new'
import { Route as AuthenticatedCollectionsCollectionIdIndexRouteImport } from './routes/_authenticated/collections/$collectionId/index'
import { Route as AuthenticatedCollectionsCollectionIdEditRouteImport } from './routes/_authenticated/collections/$collectionId/edit'
import { Route as AuthenticatedCollectionsCollectionIdVocabulariesNewRouteImport } from './routes/_authenticated/collections/$collectionId/vocabularies/new'
import { Route as AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRouteImport } from './routes/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/index'
import { Route as AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRouteImport } from './routes/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/edit'
import { Route as AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRouteImport } from './routes/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
import { Route as AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRouteImport } from './routes/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/index'
import { Route as AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRouteImport } from './routes/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/collections/new',
    path: '/collections/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdIndexRoute =
  AuthenticatedCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdEditRoute =
  AuthenticatedCollectionsCollectionIdEditRouteImport.update({
    id: '/collections/$collectionId/edit',
    path: '/collections/$collectionId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdVocabulariesNewRoute =
  AuthenticatedCollectionsCollectionIdVocabulariesNewRouteImport.update({
    id: '/collections/$collectionId/vocabularies/new',
    path: '/collections/$collectionId/vocabularies/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute =
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRouteImport.update(
    {
      id: '/collections/$collectionId/vocabularies/$vocabularyId/',
      path: '/collections/$collectionId/vocabularies/$vocabularyId/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute =
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRouteImport.update(
    {
      id: '/collections/$collectionId/vocabularies/$vocabularyId/edit',
      path: '/collections/$collectionId/vocabularies/$vocabularyId/edit',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute =
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRouteImport.update(
    {
      id: '/collections/$collectionId/vocabularies/$vocabularyId/entries/new',
      path: '/collections/$collectionId/vocabularies/$vocabularyId/entries/new',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute =
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRouteImport.update(
    {
      id: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/',
      path: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute =
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRouteImport.update(
    {
      id: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit',
      path: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdIndexRoute
  '/collections/$collectionId/vocabularies/new': typeof AuthenticatedCollectionsCollectionIdVocabulariesNewRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/edit': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute
  '/collections/$collectionId/vocabularies/$vocabularyId': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/entries/new': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdIndexRoute
  '/collections/$collectionId/vocabularies/new': typeof AuthenticatedCollectionsCollectionIdVocabulariesNewRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/edit': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute
  '/collections/$collectionId/vocabularies/$vocabularyId': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/entries/new': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute
  '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/collections/$collectionId/edit': typeof AuthenticatedCollectionsCollectionIdEditRoute
  '/_authenticated/collections/$collectionId/': typeof AuthenticatedCollectionsCollectionIdIndexRoute
  '/_authenticated/collections/$collectionId/vocabularies/new': typeof AuthenticatedCollectionsCollectionIdVocabulariesNewRoute
  '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/edit': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute
  '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute
  '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/new': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute
  '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute
  '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/': typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/collections/new'
    | '/collections'
    | '/collections/$collectionId/edit'
    | '/collections/$collectionId'
    | '/collections/$collectionId/vocabularies/new'
    | '/collections/$collectionId/vocabularies/$vocabularyId/edit'
    | '/collections/$collectionId/vocabularies/$vocabularyId'
    | '/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
    | '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'
    | '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/collections/new'
    | '/collections'
    | '/collections/$collectionId/edit'
    | '/collections/$collectionId'
    | '/collections/$collectionId/vocabularies/new'
    | '/collections/$collectionId/vocabularies/$vocabularyId/edit'
    | '/collections/$collectionId/vocabularies/$vocabularyId'
    | '/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
    | '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'
    | '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/collections/new'
    | '/_authenticated/collections/'
    | '/_authenticated/collections/$collectionId/edit'
    | '/_authenticated/collections/$collectionId/'
    | '/_authenticated/collections/$collectionId/vocabularies/new'
    | '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/edit'
    | '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/'
    | '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
    | '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'
    | '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/': {
      id: '/_authenticated/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/edit': {
      id: '/_authenticated/collections/$collectionId/edit'
      path: '/collections/$collectionId/edit'
      fullPath: '/collections/$collectionId/edit'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/vocabularies/new': {
      id: '/_authenticated/collections/$collectionId/vocabularies/new'
      path: '/collections/$collectionId/vocabularies/new'
      fullPath: '/collections/$collectionId/vocabularies/new'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/': {
      id: '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/'
      path: '/collections/$collectionId/vocabularies/$vocabularyId'
      fullPath: '/collections/$collectionId/vocabularies/$vocabularyId'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/edit': {
      id: '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/edit'
      path: '/collections/$collectionId/vocabularies/$vocabularyId/edit'
      fullPath: '/collections/$collectionId/vocabularies/$vocabularyId/edit'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/new': {
      id: '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
      path: '/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
      fullPath: '/collections/$collectionId/vocabularies/$vocabularyId/entries/new'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/': {
      id: '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/'
      path: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId'
      fullPath: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit': {
      id: '/_authenticated/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'
      path: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'
      fullPath: '/collections/$collectionId/vocabularies/$vocabularyId/entries/$entryId/edit'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
  AuthenticatedCollectionsCollectionIdEditRoute: typeof AuthenticatedCollectionsCollectionIdEditRoute
  AuthenticatedCollectionsCollectionIdIndexRoute: typeof AuthenticatedCollectionsCollectionIdIndexRoute
  AuthenticatedCollectionsCollectionIdVocabulariesNewRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesNewRoute
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute: typeof AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  AuthenticatedCollectionsCollectionIdEditRoute:
    AuthenticatedCollectionsCollectionIdEditRoute,
  AuthenticatedCollectionsCollectionIdIndexRoute:
    AuthenticatedCollectionsCollectionIdIndexRoute,
  AuthenticatedCollectionsCollectionIdVocabulariesNewRoute:
    AuthenticatedCollectionsCollectionIdVocabulariesNewRoute,
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute:
    AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEditRoute,
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute:
    AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdIndexRoute,
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute:
    AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesNewRoute,
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute:
    AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdEditRoute,
  AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute:
    AuthenticatedCollectionsCollectionIdVocabulariesVocabularyIdEntriesEntryIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
